
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author darth
 */
public class TimerFrame extends javax.swing.JFrame {

    /**
     * Creates new form TimerFrame
     */
    public TimerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digitValue = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        showDigit = new javax.swing.JButton();
        AddOne = new javax.swing.JButton();
        oneSecsDisplay = new javax.swing.JButton();
        oneSecs = new javax.swing.JTextField();
        showOneSecs = new javax.swing.JButton();
        tenSecsDisplay = new javax.swing.JButton();
        tenSecs = new javax.swing.JTextField();
        showTenSecs = new javax.swing.JButton();
        oneMinsDisplay = new javax.swing.JButton();
        oneMins = new javax.swing.JTextField();
        showOneMins = new javax.swing.JButton();
        tenMinsDisplay = new javax.swing.JButton();
        tenMins = new javax.swing.JTextField();
        showTenMins = new javax.swing.JButton();
        startTimer = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        stopAfterMins = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stopAfterSecs = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digital Timer");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        digitValue.setText("000");
        getContentPane().add(digitValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 62, -1));

        jTextField1.setBackground(new java.awt.Color(0, 0, 255));
        jTextField1.setText("   ");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 60, -1));

        jTextField2.setBackground(new java.awt.Color(0, 0, 255));
        jTextField2.setText("   ");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 20, 60));

        jTextField3.setBackground(new java.awt.Color(0, 0, 255));
        jTextField3.setText("   ");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 20, 60));

        jTextField4.setBackground(new java.awt.Color(0, 0, 255));
        jTextField4.setText("   ");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 60, -1));

        jTextField5.setBackground(new java.awt.Color(0, 0, 255));
        jTextField5.setText("   ");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 20, 60));

        jTextField6.setBackground(new java.awt.Color(0, 0, 255));
        jTextField6.setText("   ");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 20, 60));

        jTextField7.setBackground(new java.awt.Color(0, 0, 255));
        jTextField7.setText("   ");
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 60, -1));

        showDigit.setText("Show the digit");
        showDigit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDigitActionPerformed(evt);
            }
        });
        getContentPane().add(showDigit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, -1));

        AddOne.setText("Add 1");
        AddOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOneActionPerformed(evt);
            }
        });
        getContentPane().add(AddOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, -1, -1));

        oneSecsDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecsDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 140, 180));

        oneSecs.setText("000");
        oneSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 70, -1));

        showOneSecs.setText("showOneSecs");
        showOneSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOneSecsActionPerformed(evt);
            }
        });
        getContentPane().add(showOneSecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, -1, -1));

        tenSecsDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenSecsDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(tenSecsDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 140, 180));

        tenSecs.setText("000");
        tenSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenSecsActionPerformed(evt);
            }
        });
        getContentPane().add(tenSecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 70, -1));

        showTenSecs.setText("showTenSecs");
        showTenSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTenSecsActionPerformed(evt);
            }
        });
        getContentPane().add(showTenSecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, -1, -1));

        oneMinsDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneMinsDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(oneMinsDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 140, 180));

        oneMins.setText("000");
        oneMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneMinsActionPerformed(evt);
            }
        });
        getContentPane().add(oneMins, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 70, -1));

        showOneMins.setText("showOneMins");
        showOneMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOneMinsActionPerformed(evt);
            }
        });
        getContentPane().add(showOneMins, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, -1));

        tenMinsDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenMinsDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(tenMinsDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 140, 180));

        tenMins.setText("000");
        tenMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenMinsActionPerformed(evt);
            }
        });
        getContentPane().add(tenMins, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 70, -1));

        showTenMins.setText("showTenMins");
        showTenMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTenMinsActionPerformed(evt);
            }
        });
        getContentPane().add(showTenMins, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        startTimer.setText("Start");
        startTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimerActionPerformed(evt);
            }
        });
        getContentPane().add(startTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, -1, -1));

        stop.setText("End");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        getContentPane().add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, -1, -1));

        stopAfterMins.setText("99");
        getContentPane().add(stopAfterMins, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 40, -1));

        jLabel1.setText("Stop timer at:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        jLabel2.setText("Minutes:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        stopAfterSecs.setText("59");
        stopAfterSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopAfterSecsActionPerformed(evt);
            }
        });
        getContentPane().add(stopAfterSecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 40, -1));

        jLabel3.setText("Seconds:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void showDigitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDigitActionPerformed
        int digit1 = Integer.parseInt(digitValue.getText());
        if (digit1 == 0) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(false); // not shown
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
          }
        else if (digit1 == 1) {
            jTextField1.setVisible(false); // not shown
            jTextField2.setVisible(false); // not shown
            jTextField3.setVisible(true);
            jTextField4.setVisible(false); // not shown
            jTextField5.setVisible(false); // not shown
            jTextField6.setVisible(true);
            jTextField7.setVisible(false); // not shown
          }
        else if (digit1 == 2) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(false); // not shown
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(false); // not shown
            jTextField7.setVisible(true);
          }
        else if (digit1 == 3) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(false); // not shown
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(false); // not shown
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
          }
        else if (digit1 == 4) {
            jTextField1.setVisible(false); // not shown
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(false); // not shown
            jTextField7.setVisible(false); // not shown
          }
        else if (digit1 == 5) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(false); // not shown
            jTextField4.setVisible(true);
            jTextField5.setVisible(false); // not shown
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
          }
        else if (digit1 == 6) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(false); // not shown
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
          }
        else if (digit1 == 7) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(false);
            jTextField3.setVisible(true);
            jTextField4.setVisible(false); // not shown
            jTextField5.setVisible(false); // not shown
            jTextField6.setVisible(true);
            jTextField7.setVisible(false); // not shown
          }
        else if (digit1 == 8) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
          }
        else {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(false); // not shown
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
          }
    }//GEN-LAST:event_showDigitActionPerformed

    private void AddOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOneActionPerformed
        int digit1 = Integer.parseInt(digitValue.getText());
        int ones = Integer.parseInt(oneSecs.getText());
        int tens = Integer.parseInt(tenSecs.getText());
        int mins1 = Integer.parseInt(oneMins.getText());
        int min10 = Integer.parseInt(tenMins.getText());
        int secs = Integer.parseInt(stopAfterSecs.getText());
        int mins = Integer.parseInt(stopAfterMins.getText());
        int time = ones + (tens * 10) + (mins1 * 60) + (min10 * 600);
        int stopAt = secs + (mins * 60);
        
        if (time >= stopAt) {
            //Do nothing
        }
        else {
            digit1 = digit1 + 1;
            if (digit1 > 9) {
                digit1 = 0;
                ones = ones + 1;
                digitValue.setText("00" + Integer.toString(digit1));
                oneSecs.setText("00" + Integer.toString(ones));
                oneSecsDisplayActionPerformed(evt);
            }
            else {
                digitValue.setText("00" + Integer.toString(digit1));
            }
            showDigitActionPerformed(evt);
        }
    }//GEN-LAST:event_AddOneActionPerformed

    private void oneSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneSecsActionPerformed

    private void oneSecsDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsDisplayActionPerformed
        int ones = Integer.parseInt(oneSecs.getText());
        int tens = Integer.parseInt(tenSecs.getText());
        if (ones > 9) {
            ones = 0;
            tens = tens + 1;
            oneSecs.setText("00" + Integer.toString(ones));
            tenSecs.setText("00" + Integer.toString(tens));
            oneSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\0.png"));
            tenSecsDisplayActionPerformed(evt);
        }
        else {
            oneSecs.setText("00" + Integer.toString(ones));
            if (ones == 0){
                oneSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\0.png"));
            }
            else if (ones == 1){
                oneSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\1.png"));
            }
            else if (ones == 2){
                oneSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\2.png"));
            }
            else if (ones == 3){
                oneSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\3.png"));
            }
            else if (ones == 4){
                oneSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\4.png"));
            }
            else if (ones == 5){
                oneSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\5.png"));
            }
            else if (ones == 6){
                oneSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\6.png"));
            }
            else if (ones == 7){
                oneSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\7.png"));
            }
            else if (ones == 8){
                oneSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\8.png"));
            }
            else {
                oneSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\9.png"));
            }
        }
    }//GEN-LAST:event_oneSecsDisplayActionPerformed

    private void showOneSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOneSecsActionPerformed
        oneSecsDisplayActionPerformed(evt);
    }//GEN-LAST:event_showOneSecsActionPerformed

    private void tenSecsDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenSecsDisplayActionPerformed
        int tens = Integer.parseInt(tenSecs.getText());
        int mins1 = Integer.parseInt(oneMins.getText());
        if (tens > 5) {
            tens = 0;
            mins1 = mins1 + 1;
            tenSecs.setText("00" + Integer.toString(tens));
            oneMins.setText("00" + Integer.toString(mins1));
            tenSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\0.png"));
            oneMinsDisplayActionPerformed(evt);
        }
        else {
            tenSecs.setText("00" + Integer.toString(tens));
            if (tens == 0){
                tenSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\0.png"));
            }
            else if (tens == 1){
                tenSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\1.png"));
            }
            else if (tens == 2){
                tenSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\2.png"));
            }
            else if (tens == 3){
                tenSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\3.png"));
            }
            else if (tens == 4){
                tenSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\4.png"));
            }
            else {
                tenSecsDisplay.setIcon(new javax.swing.ImageIcon("H:\\5.png"));
            }
        }
    }//GEN-LAST:event_tenSecsDisplayActionPerformed

    private void tenSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenSecsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenSecsActionPerformed

    private void showTenSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTenSecsActionPerformed
        tenSecsDisplayActionPerformed(evt);
    }//GEN-LAST:event_showTenSecsActionPerformed

    private void oneMinsDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneMinsDisplayActionPerformed
        int mins1 = Integer.parseInt(oneMins.getText());
        int mins10 = Integer.parseInt(tenMins.getText());
        if (mins1 > 9) {
            mins1 = 0;
            mins10 = mins10 + 1;
            oneMins.setText("00" + Integer.toString(mins1));
            tenMins.setText("00" + Integer.toString(mins10));
            oneMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\0.png"));
            tenMinsDisplayActionPerformed(evt);
        }
        else {
            oneMins.setText("00" + Integer.toString(mins1));
            if (mins1 == 0){
                oneMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\0.png"));
            }
            else if (mins1 == 1){
                oneMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\1.png"));
            }
            else if (mins1 == 2){
                oneMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\2.png"));
            }
            else if (mins1 == 3){
                oneMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\3.png"));
            }
            else if (mins1 == 4){
                oneMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\4.png"));
            }
            else if (mins1 == 5){
                oneMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\5.png"));
            }
            else if (mins1 == 6){
                oneMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\6.png"));
            }
            else if (mins1 == 7){
                oneMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\7.png"));
            }
            else if (mins1 == 8){
                oneMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\8.png"));
            }
            else {
                oneMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\9.png"));
            }
        }
    }//GEN-LAST:event_oneMinsDisplayActionPerformed

    private void oneMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneMinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneMinsActionPerformed

    private void showOneMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOneMinsActionPerformed
        oneMinsActionPerformed(evt);
    }//GEN-LAST:event_showOneMinsActionPerformed

    private void tenMinsDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenMinsDisplayActionPerformed
        int mins10 = Integer.parseInt(tenMins.getText());
        if (mins10 > 9) {
            mins10 = 0;
            tenMins.setText("00" + Integer.toString(mins10));
            tenMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\0.png"));
        }
        else {
            tenMins.setText("00" + Integer.toString(mins10));
            if (mins10 == 0){
                tenMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\0.png"));
            }
            else if (mins10 == 1){
                tenMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\1.png"));
            }
            else if (mins10 == 2){
                tenMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\2.png"));
            }
            else if (mins10 == 3){
                tenMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\3.png"));
            }
            else if (mins10 == 4){
                tenMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\4.png"));
            }
            else if (mins10 == 5){
                tenMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\5.png"));
            }
            else if (mins10 == 6){
                tenMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\6.png"));
            }
            else if (mins10 == 7){
                tenMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\7.png"));
            }
            else if (mins10 == 8){
                tenMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\8.png"));
            }
            else {
                tenMinsDisplay.setIcon(new javax.swing.ImageIcon("H:\\9.png"));
            }
        }
    }//GEN-LAST:event_tenMinsDisplayActionPerformed

    private void showTenMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTenMinsActionPerformed
        tenMinsDisplayActionPerformed(evt);
    }//GEN-LAST:event_showTenMinsActionPerformed

    private void tenMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenMinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenMinsActionPerformed

    private void startTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimerActionPerformed
        javax.swing.Timer tm = new javax.swing.Timer(100, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                AddOneActionPerformed(evt);
            }
        });  //curly bracket then round bracket 
        tm.start();  
    }//GEN-LAST:event_startTimerActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_stopActionPerformed

    private void stopAfterSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopAfterSecsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopAfterSecsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOne;
    private javax.swing.JTextField digitValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField oneMins;
    private javax.swing.JButton oneMinsDisplay;
    private javax.swing.JTextField oneSecs;
    private javax.swing.JButton oneSecsDisplay;
    private javax.swing.JButton showDigit;
    private javax.swing.JButton showOneMins;
    private javax.swing.JButton showOneSecs;
    private javax.swing.JButton showTenMins;
    private javax.swing.JButton showTenSecs;
    private javax.swing.JButton startTimer;
    private javax.swing.JButton stop;
    private javax.swing.JTextField stopAfterMins;
    private javax.swing.JTextField stopAfterSecs;
    private javax.swing.JTextField tenMins;
    private javax.swing.JButton tenMinsDisplay;
    private javax.swing.JTextField tenSecs;
    private javax.swing.JButton tenSecsDisplay;
    // End of variables declaration//GEN-END:variables
}
